### ISSUE TITLE
categorized style needs invert

### ISSUE THREAD

**Issue by riccardoklinger** [nyalldawson/slyr#100]
The original ESRI style in this MXD:
![image](https://user-images.githubusercontent.com/7377897/89732763-47cc5100-da51-11ea-886d-c18f2db1d1a7.png)
the converted style in QGIS:
![image](https://user-images.githubusercontent.com/7377897/89732781-5f0b3e80-da51-11ea-8d77-6e6ae831634b.png)

**Comment by nyalldawson** [comment]
Any chance of linking/emailing the project and data?

**Comment by nyalldawson** [comment]
Actually - no need for data. I've confirmed and fixed.

**Comment by nyalldawson** [comment]
(updated licensed version will be published shortly)
