### ISSUE TITLE
WMS is not converted properly

### ISSUE THREAD

**Issue by riccardoklinger** [nyalldawson/slyr#101]
I have a basic project - [wms.zip](https://github.com/nyalldawson/slyr/files/5047645/wms.zip)
 -  containing a single [WMS](htts://ows.terrestris.de/osm/service?SERVICE=WMS) 
![image](https://user-images.githubusercontent.com/7377897/89734151-9cc09500-da5a-11ea-8d57-9614c587d83d.png)

this is not rendered properly in qgis:
![image](https://user-images.githubusercontent.com/7377897/89734182-db564f80-da5a-11ea-81bb-c777ad5ec5bb.png)
Even when I reselect the EPSG code with 4326, I can't see the WMS in QGIS:
![image](https://user-images.githubusercontent.com/7377897/89734239-32f4bb00-da5b-11ea-933d-965f28f010f6.png)

Network logger in QGIS 3.14 shows this as example:
curl 'http://ows.terrestris.de/osm/service?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=63.14340104542608856,-56,180,-46.23376932412168117&SRS=CRS:84&WIDTH=536&HEIGHT=45&LAYERS=SRTM30-Colored&STYLES=&FORMAT=image/jpeg&DPI=192&MAP_RESOLUTION=192&FORMAT_OPTIONS=dpi:192' -H 'User-Agent: Mozilla/5.0 QGIS/31401'  --compressed

**Comment by nyalldawson** [comment]
This is an upstream QGIS bug -- it will be fixed by https://github.com/qgis/QGIS/pull/38213 .
