### ISSUE TITLE
Missing Metadata File

### ISSUE THREAD

**Issue by sdnxgr** [nyalldawson/slyr#102]
QGIS 3.10.4
Win 7

plugin manager claims "plugin broken - missing metadata file"

Also, I'm assuming processing path to mdbtools (currently under C:\Windows\mdbtools) is set after successful plugin installation. Correct?
Apologies for any simple mistake on my part.

**Comment by nyalldawson** [comment]
Did you manually install the plugin? I'd recommend using the version from the plugin repository now, as it avoids the potential issues with unzipping the wrong folder or path.

You need to manually set the path to where you extracted the mdbtools files -- there's a panel in the Options - SLYR dialog for that.

**Comment by sdnxgr** [comment]
That works, thank you.
