### ISSUE TITLE
The tool fails while converting .style to xml

### ISSUE THREAD

**Issue by 1milenac** [nyalldawson/slyr#112]
Hi, 

I am trying to convert .style to xml but the tools fails after a few seconds and return this error. Not sure how to solve it. The output xml is empty.
![image](https://user-images.githubusercontent.com/56932184/140492601-b225cda3-3f2d-4e11-a90e-23ba07b3bfcf.png)

 -  QGIS 3.20.2

**Comment by nyalldawson** [comment]
Are you able to attach the style file?

**Comment by 1milenac** [comment]
unfortunately not as It cannot be shared outside of the organization

**Comment by nyalldawson** [comment]
Could you email it to nyall@north-road.com?

**Comment by fabianshenk** [comment]
https://opengislab.com/blog/2019/3/16/converting-esri-styles-to-qgis-styles-using-slyr

Hello. I am putting in my 2 cents.

**Comment by oguerrarea** [comment]
I have a similar issue. Attached is the style file
[PRUEBA_50K.zip](https://github.com/nyalldawson/slyr/files/7566414/PRUEBA_50K.zip)

**Comment by oguerrarea** [comment]
Thank you for the effort Nyall. Works quite fine for the file I send, but (unfortunately) still not working for more bigger and complicated style files.

**Comment by nyalldawson** [comment]
@oguerrarea are you able to attach one of those?

**Comment by oguerrarea** [comment]
[OAGR_2021.zip](https://github.com/nyalldawson/slyr/files/7628359/OAGR_2021.zip)
Dear Nyall, here is the bigger style file. Thank you.
OG

**Comment by nyalldawson** [comment]
Thanks @oguerrarea! Seems the ordering of columns in the .style database is different in that file. I wasn't previously aware that that was possible..! 

I'll push a fix shortly

**Comment by nyalldawson** [comment]
@oguerrarea fixed in the version just pushed!

**Comment by oguerrarea** [comment]
Thank you again Nyall, works fine now. 
OG
