### ISSUE TITLE
Import Error: cannot import name 'StyleDropHandler'

### ISSUE THREAD

**Issue by esnyder-rve** [nyalldawson/slyr#125]
**Describe the bug**
Updated the plugin to version 4.0.0, and got this error from the First Aid plugin:

    ImportError
    cannot import name 'StyleDropHandler' from 'slyr_community.qgis_plugin.integrations' (C:\...\slyr_community\qgis_plugin\integrations\__init__.py)

**To Reproduce**
1. Upgrade plugin
2. See error

**Screenshots**
![Screenshot 2022-01-20 084731](https://user-images.githubusercontent.com/61027950/150350758-1d436ae6-b0d9-4e57-b393-fc78a4c1f28c.png)

**Desktop Config:**
 - OSGeo4W Install
 - OS: Windows 10 Version 2009
 - QGIS release: 3.22.3
 - DataPlotly release: 4.12.0-1

**Additional context**
None

**Comment by nyalldawson** [comment]
Should be enough to just restart qgis to clear this
