### ISSUE TITLE
Convert lyr to qml

### ISSUE THREAD

**Issue by SabrinaCasucci** [nyalldawson/slyr#127]
Dear Nyall, 
I downloaded the latest version of your plugin yesterday and converting a lyr file containing different symbols, an error occurred (cfr. image) but I can't understand which symbol it refers to.
Could you give me some suggestions?

Thanks for your very important work.

Sabrina

![errore](https://user-images.githubusercontent.com/96534478/150511804-8c17d745-30ce-4067-a0db-701eaad686ef.png)

**Comment by nyalldawson** [comment]
This is just a warning -- it's shown in situations where the results may differ from the original arcmap appearance. It's for reference only, the conversion will still proceed.

**Comment by SabrinaCasucci** [comment]
Thank you!
