### ISSUE TITLE
LYR file extraction

### ISSUE THREAD

**Issue by nyalldawson** [nyalldawson/slyr#16]
We need to convert the VBA code from the appendix in  http://www.diva-portal.se/smash/get/diva2:1086367/FULLTEXT01.pdf to Python, and determine how symbols are stored within lyr files, and whether the same parser as the style parser can be reused directly on lyr files (breaking the dependence on having ESRI products to open lyr files and convert to style databases)

**Comment by kaplanlior** [comment]
Hi @nyalldawson , thanks for this tool/plugin.

The README.md file references .lyr support, but this issue obviously mean it's not yet available. Can the README.md be changed till this issue is resolved?

**Comment by nyalldawson** [comment]
Done in commercial version
