### ISSUE TITLE
Failed to convert polygon fill style "Expected 01 at 0x30, got b'14"

### ISSUE THREAD

**Issue by iqnaul** [nyalldawson/slyr#36]
I'm having issue when try to convert my custom arcgis style which consists of polygon fill, the slyr log stated that: Error reading symbol Mangrove: Expected 01 at 0x30, got b'14' (mangrove is one of my style class).
I'm using QGIS 3.2 on Windows10-x64 and already setup the mdbtools-win path, my style file is attached
![2018-09-05 05_09_34-convert esri style to qgis xml](https://user-images.githubusercontent.com/3491977/45060538-72c20380-b0ca-11e8-8283-01dbcd798ca9.png)

[PL.zip](https://github.com/nyalldawson/slyr/files/2350425/PL.zip)

**Comment by nyalldawson** [comment]
Thank you!

Can you please attach screenshots of the expected symbol properties too? (Make sure you also attach screenshots of the color dialogs)

**Comment by nyalldawson** [comment]
Please attach screenshots of both the fill color and outline color dialogs too (i.e. the one with "color selector" at the top and the choice of RGB/CMYK/etc)

**Comment by iqnaul** [comment]
Hi, sorry for the delayed response.
This is the fill color dialogs:
![fillcolor](https://user-images.githubusercontent.com/3491977/45132228-5c937080-b1ba-11e8-84e9-11a926fad11c.png)

This is the outline color:
![outline-color](https://user-images.githubusercontent.com/3491977/45132254-703ed700-b1ba-11e8-81a5-32830f416b2e.png)

**Comment by nyalldawson** [comment]
Thank you!

**Comment by nyalldawson** [comment]
Fixed
