### ISSUE TITLE
Failed to convert Fill symbol

### ISSUE THREAD

**Issue by peterisb** [nyalldawson/slyr#39]
Failed to convert Fill symbols (probably not only), tested with:
QGIS version 3.2.2-Bonn, QGIS code revision 75cac03, Ubuntu 16.04
SLYR - actual master

```
Critical: Traceback (most recent call last):
   File "/home/testuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/slyr/qgis_plugin/algorithms.py", line 122, in processAlgorithm
     raw_symbols = Extractor.extract_styles(input_file, symbol_type, mdbtools_path=mdbtools_folder)
   File "/home/testuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/slyr/bintools/extractor.py", line 64, in extract_styles
     symbol_id, name, category, blob, tags = r.split(Extractor.__DELIMITER)
 ValueError: not enough values to unpack (expected 5, got 4)
 
```

Tested on resource and style samples provided by Latvian Geospatial Information Agency for  ArcGIS 9.2. and 9.3. Samples for download (style and resource files with data samples) http://map.lgia.gov.lv/index.php?lang=2&cPath=4_15_31&txt_id=43

**Comment by nyalldawson** [comment]
I'm not able to connect to http://map.lgia.gov.lv (maybe it's geoblocked?) Could you post a style here?

**Comment by nyalldawson** [comment]
https://github.com/nyalldawson/slyr/commit/b06419863fe13c2da8e8f69d2d3d01c2bcfdbf64 gets this a bit closer - but it hangs when reading one of the line styles here. More work is needed.

**Comment by peterisb** [comment]
Now seems that http://map.lgia.gov.lv is up again. In any case I upload sample SHP files and expected visualisation in PDF.
[vtk_shp.zip](https://github.com/nyalldawson/slyr/files/2365284/vtk_shp.zip)
[vtk_pdf.pdf](https://github.com/nyalldawson/slyr/files/2365285/vtk_pdf.pdf)

**Comment by nyalldawson** [comment]
Fixed in master -- at least, the exception is fixed. The majority of this style however consists of symbol types which aren't fully supported yet (but are coming shortyl!)
