### ISSUE TITLE
Where to put the mdbtools binaries

### ISSUE THREAD

**Issue by FHList** [nyalldawson/slyr#52]
Hi, 
I want to test your program in QGIS but I dont know where I have to put the the mdbtools binaries, so I can´t run this plugin.

Thank you and best regards

**Comment by nyalldawson** [comment]
If you look in Options, Processing, Providers, SLYR you'll see an option to set the mdbtools path.

**Comment by nyalldawson** [comment]
Currently only style files - see https://github.com/nyalldawson/slyr/issues/16

**Comment by koyo-jakanees** [comment]
Hi, Does the mdbtools be in the slyr tools folder or it can reside anywhere. I have tried setting the path, but it throws unkown error then qgis crashes.

**Comment by nyalldawson** [comment]
@koyo-jakanees It can be anywhere. What platform are you running on?

**Comment by baliun** [comment]
Hi, does this matter solved? 
just installed slyr and QGIS crashed after set the mdbtools path.
i'm using QGIS 3.4 on Win10.

**Comment by nyalldawson** [comment]
@baliun did you get an error message? Was it a QGIS crash, or a slyr crash? Which 3.4 version are you running?

**Comment by koyo-jakanees** [comment]
@nyalldawson  i was getting the crash info on linux{Manjaro linux, Qgis 3.4}
I tried it on windows it worked out well. ** *(Managed to convert whatsapp arcgis emoji sysmbols in lyr to qgis)* **
on linux i was getting windows compatibility issues with mdb tools thus moved to windows. Haven't used it on linux for awhile now. will try and retry and give an update, upgraded to QGIS 3.6

**Comment by skytwosea** [comment]
Hello, I am trying to run slyr on Kubuntu. I have installed mdbtools via apt, they are available on system path (tested via 'which mdb-export'). I went in to qgis settings for slyr and set the path to the result of 'which mdb-export' = /usr/bin/  but the system keeps complaining that it cannot find the mdb binaries. Any thoughts?

**Comment by nyalldawson** [comment]
@skytwosea 

Try putting the full path including "mdb-export". Eg "/usr/bin/mdb-export"

**Comment by skytwosea** [comment]
@nyalldawson I will reply to this in the proper bug report I opened, #128 ... sorry for writing into a closed thread
