### ISSUE TITLE
This plugin is broken - missing metadata file.

### ISSUE THREAD

**Issue by rekafarkas1993** [nyalldawson/slyr#89]
![slyr_broken](https://user-images.githubusercontent.com/45092938/48610457-224a0a80-e985-11e8-880a-cbbe8413e8eb.jpg)

I extracted the plugin to the right folder, and this is the error I'm getting when I try to enable it in the plugins window.

Thank you for your answer.

**Comment by nyalldawson** [comment]
This indicates that the zip hasn't been extracted to the right location. When it's extracted correctly you should see:

    python/plugins/slyr/metadata.txt

I.e. the metadata file must sit in a slyr folder directly under plugins.
