### ISSUE TITLE
frustrated

### ISSUE THREAD

**Issue by roberlane65** [nyalldawson/slyr#90]
hi. I love the concept behind this and cant wait for the layer to sld version.
I am trying to run style_to_qgis_xml but I am getting frustrated by the prerequisites.
It looks like the original code was built to run on linux and I am trying to run it in windows with the starting point of the ESRI python 64 bit (which I don't want to wreck as I am running quite a few complex processes) 
I also installed qgis 2.18 a few months ago
On my initial run of  style_to_qgis_xmlI had error messages regarding import failures which I think I fixed by setting PYTHONPATH to look at my qgis python extras.
Then I had messages about not being able to import SIP. When I tried to install this, I got 
ImportError: No module named Cython.Distutils"
Then looking for info on this it says cython is another programming language, but does not reveal how to really fix the issue.
Can anyone assist?

**Comment by nyalldawson** [comment]
Are you trying to run standalone? This should partially work, but only the "parsing" part of the library and not the conversion to QGIS symbology.

Keep in mind that it's Python 3 + Qt 5 only, so you won't be able to use either ESRI supplied python (which is version 2) or QGIS 2.18 python (version 2 + qt 4).

Basically it's designed to work out of the box for a QGIS 3.4 setup only.**

** Although like I said, it should be possible to directly to the parsing step alone without requiring QGIS.

**Comment by roberlane65** [comment]
Thanks for that - I could not find anything in the doco that said it was for python 3.
I'll have to rethink.

**Comment by nyalldawson** [comment]
No worries!
