### ISSUE TITLE
MXD support

### ISSUE THREAD

**Issue by baerbock** [nyalldawson/slyr#91]
Dear Niall,

does this Open Source version currently support mxd input, e.g. https://viewer.nationalmap.gov/tools/topotemplate/contents/Topo_TNM_Style_Template.zip ?

**Comment by nyalldawson** [comment]
@baerbock 

MXDs are not supported yet -- basically the way style/LYR/MXD files are structured we need to "build up" to these. MXDs basically contain multiple LYR files themselves, and we need to be able to reliably parse LYR files before we'll be able to start work on MXD documents.

So it's coming, but not yet. We're aiming for September-October 2019 for MXD support, which will initially be included in the full SLYR version only, and then at a later stage will be released to the open source version. See https://north-road.com/slyr/ for details.
