### ISSUE TITLE
error message: "This plugin is defect. Meta data are missing"

### ISSUE THREAD

**Issue by geodennis** [nyalldawson/slyr#92]
According to the README file, I'm just supposed to add the "slyr" folder to the Python -> Plugin folder and activated it in QGIS. 

When I go to the QGIS Plugin extentions the plugin appears but I get the error message "This plugin is defect. Metadata is missing". However, there is a metadata.txt file inside the "slyr" folder. 
Does anyone have any ideas what the problem might be and how to solve it? 

I'm using QGIS 3.4.6.

**Comment by nyalldawson** [comment]
@geodennis 

Can you confirm that you see the metadata.txt directly under the python/plugins/slyr ? It must not be under any subfolder under slyr (eg, you should not have "python/plugins/slyr/slyr/metadata.txt"

**Comment by geodennis** [comment]
Thanks, that was the Problem. The plugin is installed now and the Tools available. Unfortunately, the tools are not working yet. When I try to execute it I get the error message "The System can not find the Input file." 

I'm trying to add a .style file which is within a regular folder. Any idea what could be the Problem here?

**Comment by nyalldawson** [comment]
Have you installed the mdbtools binary and setup the paths to that? (see https://github.com/nyalldawson/slyr#qgis-plugin )

**Comment by geodennis** [comment]
Thanks for the support so far! I appreciate it! I'm sorry for asking noob questions. 

So, I have extracted the mdbtools and added the folder as well as all the files inside the folder into the slyr folder. When I go in QGIS to Options -> Processing -> Providers -> SLYR, the SLYR Symbol appears and it says "Location of mdbtools binaries" but I cannot select or do anything with it. 

Now my error message is "The handle is invalid".

**Comment by nyalldawson** [comment]
You should be able to double click on that row to set the path
