### ISSUE TITLE
Couldn't load plugin 'slyr' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by holamtruong** [nyalldawson/slyr#93]
Hi, 
I have a problem with installing the "slyr" plugin. My QGIS version is 3.6.0, and the Python version is 3.7.0.

![image](https://user-images.githubusercontent.com/17373475/59840120-f6a85c00-937b-11e9-82fb-6dbc8f114291.png)

**Comment by nyalldawson** [comment]
Due to time constraints, we don't offer any end-user support for this open source version of the tool -- we can only offer support for licensed customers (See https://north-road.com/slyr/). You may have some luck posting your question on gis.stackexchange.com .

**Comment by cesarcorreo** [comment]
Hi all. Same problem.
Truong Ho, did you solve it?
Thanks
