### ISSUE TITLE
test for availability of mdbtools fails on Win10

### ISSUE THREAD

**Issue by miet-t** [nyalldawson/slyr#97]
Hi,
On Win10 with QGIS 3.10.8 function "is_mdb_tools_binary_available" in "extractor.py" gives false result: in line 151 it tests every line of mdb-export.exe response for text "Usage: mdb-export", while this text is broken into 2 separate lines (see attached screenshot). Using only "Usage:" or "mdb-export.exe" for availability testing works fine.

![mdbtools-Win10](https://user-images.githubusercontent.com/60602972/89467342-b1a8da00-d775-11ea-87a0-8276188135b5.png)

**Comment by nyalldawson** [comment]
Thanks for the detailed report! New release inbound shortly...
