### ISSUE TITLE
Python error in starting the process

### ISSUE THREAD

**Issue by antzzp** [nyalldawson/slyr#98]
After I installed the plugin,I downloaded the MDB Tools and set the MDB Tools path succesfully.When I click Convert ESRI style to GPL color palette or Convert ESRI style to QGIS style XML,it occured Python error,I click the Stack trace,it showed the following picture.I get that gbk is meaning of  Chinese Internal Code Specification.
My OS is windows 7 ,qgis version is 3.14-PI .
Zheng Zhipeng from China.
![image](https://user-images.githubusercontent.com/33449027/89707301-670aa600-d99f-11ea-8610-c7869f99c6ff.png)
![image](https://user-images.githubusercontent.com/33449027/89707305-6a059680-d99f-11ea-8c1e-6e97064d0a9e.png)

**Comment by storyofblue** [comment]
I have the same problem,if you just use SLYR simply,you can do that modify the code `**Extractor.get_process_keywords()) as proc:	` like this `startupinfo=Extractor.get_process_keywords()['startupinfo']) as proc:`(it is in slyr_community\bintools\extractor.py and line 147. ).thanks for SLYR,it's awsome.

**Comment by nyalldawson** [comment]
Thanks @storyofblue  -- any chance you could submit that as a pull request?
