### ISSUE TITLE
gdb warning message misleading

### ISSUE THREAD

**Issue by riccardoklinger** [nyalldawson/slyr#99]
I am trying to use mxd import for a video.

I am using the default training data from Esri ([LINK](https://esripress.esri.com/storage/esripress/bookresources/gtkad5/datasetup.exe). Chapter 3 consists of some layers stored in a gdb. When I add it to QGIS it is stating to "decompress the gdb" All the layers in the gdb were "decompressed" using the [uncompress gdb](https://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/uncompress-file-geodatabase-data.htm) process in esri. But unfortunately no success so far to open the mxd...
[Chapter03.zip](https://github.com/nyalldawson/slyr/files/5047491/Chapter03.zip)

**Comment by nyalldawson** [comment]
@riccardoklinger 

Congratulations! --- You've found a bug in ArcMap :laughing: 

I'm hitting the same thing here. The World.gdb database is most certainly a compressed geodatabase. You can confirm this by the presence of all the .cdf files inside the .gdb folder -- these a compressed data files, and it's where all the information in that gdb is stored. Yet attempting to decompress it in ArcMap leads to the incorrect error message that the database is already decompressed...! 

I found that if you can repair this gdb by right clicking in ArcCatalog, and selecting "Export" -> "To Geodatabase (multiple)" and export all the contents to a new (non corrupted?) gdb. Then it works fine in the converted QGIS project.

I don't think there's anything we can do in SLYR/QGIS/GDAL to handle this situation, at least not until GDAL gets a native driver for reading compressed GDB files (which would then allow them to be opened in QGIS and other open-source software)
